language: cpp
# xcode8.2 == OS X 10.12: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
osx_image: xcode8.2

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libpcap-dev

install:
  - if [[ "$CXX" == "g++" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: ./scripts/run_build.sh
